config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  get 'myposts' => 'posts#myposts'
  get 'mydrafts' => 'posts#mydrafts'
  get '/users/' => 'users#index', as: 'users'
  get '/ban/:id' => 'users#ban', as: 'ban'
  get '/unban/:id' => 'users#unban', as: 'unban'
  resources :posts do
    get '/up_rate/' => 'posts#up_rate_post'
    get '/down_rate/' => 'posts#down_rate_post'
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments, dependent: :restrict_with_exception
  validates :title, :summary, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role: { user: 0, admin: 1, moderator: 2 }
  has_many :posts, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true

  def account_active?
    ban.nil?
  end

  def active_for_authentication?
    super && account_active?
  end

  def inactive_message
    account_active? ? super : :locked
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception

  add_flash_types :success, :danger, :info, :warning

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:username, :email, :password)
    end

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:username, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.author_id = current_user.id
    user = User.find(current_user.id)
    @comment.username = user.username.to_s

    @post.save
    redirect_to post_path(@post), success: 'Комментарий успешно добавлен'
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post), success: 'Комментарий успешно удален'
  end

  def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: %i[edit update destroy]

  def index
    @posts = if current_user && current_user.role != 'user'
               Post.all
             else
               Post.all.where(published: true)
             end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    authorize Post
    @post = Post.new(post_params)
    if @post.save
      if params[:new_draft]
        @post.update(published: false)
        redirect_to @post, success: 'Добавлено в черновики'
      else
        redirect_to @post, success: 'Статья успешно создана'
      end
    else
      flash.now[:danger] = 'Статья не создана'
      render :new
    end
  end

  def myposts
    @posts = Post.where(user_id: current_user.id, published: true)
    authorize @posts
  end

  def mydrafts
    @posts = Post.where(user_id: current_user.id, published: false)
    authorize @posts
  end

  def edit; end

  def up_rate_post
    @post = Post.find(params[:post_id])
    user_id = current_user.id.to_s

    if @post.up_rate.include?(user_id)
      nil
    else
      @post.down_rate.delete(user_id) if @post.down_rate.include?(user_id)
      @post.up_rate.push(user_id)
    end

    @post.save
    redirect_to @post, success: 'Действие успешно выполнено.'
  end

  def down_rate_post
    @post = Post.find(params[:post_id])
    user_id = current_user.id.to_s

    if @post.down_rate.include?(user_id)
      nil
    else
      @post.up_rate.delete(user_id) if @post.up_rate.include?(user_id)
      @post.down_rate.push(user_id)
    end

    @post.save
    redirect_to @post, success: 'Действие успешно выполнено.'
  end

  def update
    if @post.update(post_params)
      if params[:new_draft]
        @post.update(published: false)
        redirect_to @post, success: 'Добавлено в черновики'
      elsif params[:new_post]
        @post.update(published: true)
        redirect_to @post, success: 'Опубликовано'
      else
        redirect_to @post, success: 'Статья успешно обновлена'
      end
    else
      flash.now[:danger] = 'Статья не обновлена'
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success: 'Статья успешно удалена'
  end

  private

  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end

  def post_params
    req_body = params.require(:post).permit(:title, :summary, :body, :image, :remove_image, :image_cache)
    req_body[:user_id] = current_user.id

    req_body
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def ban_time(time)
    Time.zone.now + Time.zone.at(time)
  end

  def ban
    return unless user_signed_in?

    @user = User.find(params[:id])
    @time_zone = Time.zone.at(ban_time(3600 * 24 * 14))
    @user.update(ban: @time_zone)
    @user.ban = @time_zone
    @user.save
    redirect_to users_path(@user.id), success: "Успешно, пользователь: #{@user.username} получил бан до #{@user.ban}"
  end

  def unban
    return unless user_signed_in?

    @user = User.find(params[:id])
    @user.update(ban: nil)
    @user.ban = nil
    @user.save
    redirect_to users_path(@user.id), success: "Успешно, пользователь: #{@user.username} разбанен "
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(name)
    {
      success: 'alert-success',
      error: 'alert-gander',
      danger: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[name.to_sym] || name
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<%= root_path %>"> Все статьи</a>
            </li>
          </ul>
          <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
            <% if user_signed_in? %>
              <% if current_user.role == "admin" %>
                <li class="nav-item">
                  <%= link_to "Админка", users_path, class: "btn btn-outline-danger" %>
                </li>
              <% end %>
              <h5><span class="badge bg-secondary"><%= current_user.username %></span></h5>
              <li class="nav-item">
                <%= link_to "Мои посты", myposts_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Мои черновики", mydrafts_path, class: "nav-link" %>
              </li>
              <li class="nav-item nav-item-margin">
                <%= link_to "Новая статья", new_post_path, class: 'btn btn-success' %>
              </li>
              <li>
                <%= link_to "Выход", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "Вход", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Регистрация", new_user_registration_path, class: "nav-link" %>
            </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>

  <div class="container main">
    <div class="row">
      <div  class="col-md-12">
        <% flash.each do |name, message| %>
          <div class="alert <%= bootstrap_class_for(name) %>">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <%= message %>
          </div>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </div>

  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors', count: @post.errors.count) %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @post, html: { multipart: true }, url: posts_path do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group image">
    <%= f.hidden_field :image_cache %>
    <% if @post.image? %>
      <%= image_tag @post.image.thumb.url %>
      <%= f.check_box :remove_image %> Удалить файл
    <% end %>
    <div class="image">
      <%= f.file_field :image %>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
    <%= link_to 'Назад', :back, class: 'btn btn-outline-secondary' %>
    <% if @post.published? %>
      <%= f.submit "Добавить в черновики",
                   :class => "btn btn-secondary",
                   :name => "new_draft"%>
    <% else %>
      <%= f.submit "Опубликовать",
                   :class => "btn btn-success",
                   :name => "new_post"%>
    <% end %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <span>
      <time><%= post.created_at.to_date.strftime("%d %B, %Y") %></time>
      |
      <% if post.published? %>
        <span class="badge rounded-pill bg-primary">Опубликовано</span>
        |
        <span class="upRate" style="color: green"> + <%= post.up_rate.length %></span>
        /
        <span class="downRate" style="color: red">- <%= post.down_rate.length %></span>
        |
      <% else %>
        <span class="badge rounded-pill bg-secondary">Черновик</span>
      <% end %>
      Автор статьи: <span class="badge bg-secondary"><%= post.user.username %></span>
      <% if current_user %>
        <% if current_user.id == post.user_id || current_user.role != "user" %>
          |
          <%= link_to 'Изменить', edit_post_path(post) %>
          |
          <%= link_to 'Удалить', post_path(post), method: :delete, data: { confirm: 'Вы уверены?' } %>
        <% end %>
      <% end %>
      </span>
  </section>

  <section class="post-summary clearfix">
    <%= image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image? %>
    <%= post.summary %>
  </section>
</article>

app/views/posts/edit.html.erb
<h1>Редактирование статьи</h1>
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors', count: @post.errors.count) %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for :post, html: { multipart: true }, url: post_path(@post), method: :patch do |f| %>
    <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group image">
    <%= f.hidden_field :image_cache %>
    <% if @post.image? %>
      <%= image_tag @post.image.thumb.url %>
      <%= f.check_box :remove_image %> Удалить файл
    <% end %>
    <div class="image">
      <%= f.file_field :image %>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
    <%= link_to 'Назад', :back, class: 'btn btn-outline-secondary' %>
    <% if @post.published? %>
      <%= f.submit "Добавить в черновики",
                   :class => "btn btn-secondary",
                   :name => "new_draft"%>
    <% else %>
      <%= f.submit "Опубликовать",
                   :class => "btn btn-success",
                   :name => "new_post"%>
    <% end %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h1>Все статьи</h1>
<%= render @posts %>

app/views/posts/mydrafts.html.erb
<h1>Мои черновики</h1>
<%= render @posts %>

app/views/posts/myposts.html.erb
<h1>Мои статьи</h1>
<%= render @posts %>

app/views/posts/new.html.erb
<h1>Новая статья</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<article class="post">
  <section class="post-head">
    <h1><%= @post.title %></h1>
    <span>
      <time><%= @post.created_at.to_date.strftime("%d %B, %Y") %></time>
      |
      <% if @post.published? %>
        <span class="badge rounded-pill bg-primary">Опубликовано</span>
        |
        <span class="upRate" style="color: green"> + <%= @post.up_rate.length %></span>
        /
        <span class="downRate" style="color: red">- <%= @post.down_rate.length %></span>
        |
      <% else %>
        <span class="badge rounded-pill bg-secondary">Черновик</span>
      <% end %>
      Автор статьи: <span class="badge bg-secondary"><%= @post.user.username %></span>
      <% if current_user %>
        <% if current_user.id == @post.user_id || current_user.role != "user" %>

          |
          <%= link_to 'Изменить', edit_post_path(@post) %>
          |
          <%= link_to 'Удалить', post_path(@post), method: :delete, data: { confirm: 'Вы уверены?' } %>
        <% end %>
      <% end %>

    </span>
  </section>

  <section class="post-body">
    <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
    <%= @post.body %>
  </section>
  <% if @post.published? %>
    <div class="btn-group">
    <%= button_to "Нравится", post_up_rate_path(@post.id), :method => :get, :class => "btn btn-outline-success btn-sm", :disabled => !current_user %>
    <%= button_to "Не нравится", post_down_rate_path(@post.id), :method => :get, :class => "btn btn-outline-danger btn-sm", :disabled => !current_user %>
    </div>
  <% end %>
</article>

<h3>Все комментарии</h3>
<% if @post.comments.length < 1 %>
  <br>
  <p><span>Пока нет комментариев</span></p>
  <br/>
<% end %>

<article class="comment">
<% @post.comments.each do |comment| %>
  <div class="form-group">
        <span class="badge bg-secondary"><%= comment.username %></span>: <%= comment.body %>
    <div class="buttons">
      <% if current_user && (current_user.id == comment.author_id || current_user.role == ("admin" && "moderator")) %>
        <%= link_to "Удалить", [comment.post, comment], method: :delete,
                  data: { confirm: 'Хотите удалить комментарий?' }
        %>
      <% end %>
    </div>
  </div>
<% end %>
</article>

<% unless current_user %>
  <div>
    Авторизуйтесь, чтобы оценивать посты и оставлять комментарии.
  </div>
<% end %>


<% if current_user %>
  <h3>Добавить комментарий</h3>
  <%= form_for [@post, @post.comments.build] do |f| %>

    <div class="form-group">
      <%= f.label :'Текст комментария' %>
      <%= f.text_area :body, class: 'form-control', rows: '5' %>
    </div>

    <div class="form-group">
      <%= f.submit 'Отправить', class: 'btn btn-success' %>
    </div>
  <% end %>
<% end %>

app/views/users/_user.html.erb
<h5><%= user.username %> - <%= user.email %>
<span class="badge rounded-pill bg-primary"><%= user.role %></span>
<% if current_user  %>
  <% if current_user.role == "admin" && user.role != "admin" %>
    <% if !user.ban || user.ban <= Time.zone.now %>
      <%= link_to 'Забанить на 14 дней', ban_path(user.id) %>
    <% else %>
      <%= link_to 'Разбанить', unban_path(user.id) %>
    <% end %>
  <% end %>
<% end %>
</h5>

app/views/users/index.html.erb
<ul class="users">
  <%= render @users %>
</ul>